### ISSUE TITLE
Error in the first step pipeline while running motus-extender.py prepare -w test_extension/extension

### ISSUE THREAD

**Issue by sssuyi** [motu-tool/mOTUs-extender#3]
HI
in the first step: mOTUs extender - prepare
, I just ran the following code: python mOTUs-extender/mOTUs-extender/motus-extender.py prepare -w test_extension/extension, then it shown an error.

input:

`python mOTUs-extender/mOTUs-extender/motus-extender.py prepare -w test_extension/extension`

output:

`2023-10-12 11:53:50,891 INFO: Starting mOTUs-extender`

`2023-10-12 11:53:50,892 INFO: Creating work folder /mnt/sdb/njguest/sy/test_extension/extension`

`2023-10-12 11:53:50,939 INFO: Downloading mOTUs 3.1.0 database`

`2023-10-12 11:53:50,948 INFO: Executing: curl https://zenodo.org/record/7778108/files/db_mOTU_v3.1.0.tar.gz -o/mnt/sdb/njguest/sy/test_extension/extension/orig_db/db_mOTU_v3.1.0.tar.gz`

`% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0`

`curl: (7) Failed to connect to zenodo.org port 443: Connection refused`

`2023-10-12 11:53:51,317 ERROR: Command curl https://zenodo.org/record/7778108/files/db_mOTU_v3.1.0.tar.gz -o/mnt/sdb/njguest/sy/test_extension/extension/orig_db/db_mOTU_v3.1.0.tar.gz failed with message:       None`

`2023-10-12 11:53:51,317 INFO: mOTUs-extender finished with error code 1`

I hope to help! from you soon.

**Comment by hjruscheweyh** [comment]
Hello @sssuyi 

The issue looks like the mOTUs-extender cant download the database. I think that the Zenodo services were down for a few hours last week. Maybe you were just unlucky to use the mOTUs extender in their maintenance period. 

Try again and let me know if it works.

best,
hans

**Comment by sssuyi** [comment]
hi hans
this time, I just ran the following code: python mOTUs-extender/mOTUs-extender/motus-extender.py prepare -w test_extension/extension, the error message this time has changed.
then it shown as follows:
`2023-10-19 09:46:04,668 INFO: Starting mOTUs-extender`
`2023-10-19 09:46:04,670 INFO: Creating work folder /mnt/sdb/weizhonglab/suyi/OTU_extender/test_extension/extension`
`2023-10-19 09:46:04,692 INFO: Downloading mOTUs 3.1.0 database`
`2023-10-19 09:46:04,692 INFO: Executing: curl https://zenodo.org/record/7778108/files/db_mOTU_v3.1.0.tar.gz -o /mnt/sdb/weizhonglab/suyi/OTU_extender/test_extension/extension/orig_db/db_mOTU_v3.1.0.tar.gz
/bin/sh: curl: command not found`
`2023-10-19 09:46:04,699 ERROR: Command curl https://zenodo.org/record/7778108/files/db_mOTU_v3.1.0.tar.gz -o /mnt/sdb/weizhonglab/suyi/OTU_extender/test_extension/extension/orig_db/db_mOTU_v3.1.0.tar.gz failed with message:    None`
`2023-10-19 09:46:04,700 INFO: mOTUs-extender finished with error code 1`

so, I replaced 'curl' in the code with 'wget'.
Then, the current error message is:
`2023-10-19 10:01:53,306 INFO: Starting mOTUs-extender`
`2023-10-19 10:01:53,307 INFO: Creating work folder /mnt/sdb/weizhonglab/suyi/OTU_extender/test_extension/extension`
`2023-10-19 10:01:53,307 INFO: Downloading mOTUs 3.1.0 database`
`2023-10-19 10:01:53,307 INFO: Executing: wget https://zenodo.org/record/7778108/files/db_mOTU_v3.1.0.tar.gz -o /mnt/sdb/weizhonglab/suyi/OTU_extender/test_extension/extension/orig_db/db_mOTU_v3.1.0.tar.gz`
`2023-10-19 10:01:53,401 ERROR: Command wget https://zenodo.org/record/7778108/files/db_mOTU_v3.1.0.tar.gz -o /mnt/sdb/weizhonglab/suyi/OTU_extender/test_extension/extension/orig_db/db_mOTU_v3.1.0.tar.gz failed with message:    None`
`2023-10-19 10:01:53,402 INFO: mOTUs-extender finished with error code 1`

So , how should I address this issue?

best,
suyi

**Comment by hjruscheweyh** [comment]
Hi @sssuyi yes it seems that replacing curl with wget will do the trick. But you also need to change the -o with -O. I have pushed this change to this repo already. Thank you for finding the issue.
